intendation

diff --git a/.github/workflows/cypress_e2e.yml b/.github/workflows/cypress_e2e.yml
--- a/.github/workflows/cypress_e2e.yml
+++ b/.github/workflows/cypress_e2e.yml
@@ -74,14 +74,14 @@ jobs:
           path: docs_generation/results.json
           if-no-files-found: error
       - name: Check validation results
-        run: >-
-        if grep -q '"valid": false' docs_generation/results.json; then
-          echo "Validation failed"
-          exit 1
-        else
-          echo "Validation passed"
-          touch validation_passed.txt
-        fi
+        run: |
+          if grep -q '"valid": false' docs_generation/results.json; then
+            echo "Validation failed"
+            exit 1
+          else
+            echo "Validation passed"
+            touch validation_passed.txt
+          fi
   deploy-docs:
     needs: plugin-validation
     runs-on: ubuntu-latest
@@ -90,7 +90,7 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
       - name: Read files to copy
-        run: >-
+        run: |
           jq -r '.[] | select(.valid == true) | .filename' docs_generation/results.json | while IFS= read -r file; do
             cp "$file" docs/static/examples/
           done
